---
- name: Deploy LAMP Stack
  hosts: web
  become: yes

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Apache, MySQL, PHP
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create index page
      copy:
        content: "<h1>Advanced LAMP via Ansible 🚀</h1>"
        dest: /var/www/html/index.html
